### ISSUE TITLE
Design of `beforeinstallprompt` event object (`window.deferredPrompt`)

### ISSUE THREAD

**Issue by liuderchi** [supercycle91/desktop-pwas#1]
First of all, Thanks for your great PWA example 💯

Actually this is not an issue but more like a question out of curiosity.
I've read `App.js` and want to know how it is designed to handle installation.

https://github.com/supercycle91/desktop-pwas/blob/fe5d130820f0dc03bac39a96c50e57d975bad9df/src/App.js#L25-L33

I'm really curious about line no.30:
`window.deferredPrompt = e;`

Would it possible to store `beforeinstallprompt` event in `<App />` component state? 
Or there is something I missed so it's designed to stored at `window`?

**Comment by david-novicki** [comment]
Thanks!

There is no need to store it in the ```window```. Ideally you would want the install ability to be global but a more 'complete' React app could handle that fine.
